name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup Java JDK
        uses: actions/setup-java@v2.5.0
        with:
          distribution: adopt-hotspot
          java-version: 8
      - run: ./gradlew --info build
